GET http://localhost:8080/api/answers/1
Accept: application/json

###

POST http://localhost:8080/api/answers/
Accept: application/json
Content-Type: application/json

{
  "answerText": "New answer ",
  "userId": 1,
  "questionId": 1
}
