GET http://localhost:8080/api/comments/5
Accept: application/json

###

POST http://localhost:8080/api/comments/
Accept: application/json
Content-Type: application/json

{
  "commentText": "New comment posted from endpoints using DTO with validation",
  "userId": 1,
  "answerId": 1
}

###
