GET http://localhost:8080/api/companies/
Accept: application/json

###

POST http://localhost:8080/api/companies/
Content-Type: application/json
Accept: application/json

{
  "companyName": "Company 3"
}

###

PUT http://localhost:8080/api/companies/3
Content-Type: application/json

{
  "companyName": "New Company 3"
}

###

DELETE http://localhost:8080/api/companies/3

###
