GET http://localhost:8080/api/questions/1
Accept: application/json

###

POST http://localhost:8080/api/questions/
Content-Type: application/json

{
  "questionText": "Questionhfbvedyuvbrybvedgbfovbhrbcvxbunrbviruecnvuyvinuvxunvuivinviunvrunscinvxvgviutvsinvnkuavxmkufdbcukxvukvugrvvrvxrnvrcxvvgnvngjvnvcrgcvgsdfnxgvnsvnikvcgurckv",
  "userId": 1,
  "subTopicId": 1
}

###

POST http://localhost:8080/api/questions/like
Content-Type: application/json

{
  "userId": 1,
  "questionId": 1
}

###

POST http://localhost:8080/api/questions/filter-by/
Content-Type: application/json
Accept: application/json

{
  "likesCount": 0
}

###
