GET http://localhost:8080/api/tags/
Accept: application/json

###

POST http://localhost:8080/api/tags/
Content-Type: application/json
Accept: application/json

{
  "tagName": "Tag 5"
}

###

PUT http://localhost:8080/api/tags/4
Content-Type: application/json

{
  "tagName": "Tag 4"
}

###

DELETE http://localhost:8080/api/tags/4

###
