GET http://localhost:8080/api/topics/
Accept: application/json

###

POST http://localhost:8080/api/topics/
Content-Type: application/json
Accept: application/json

{
  "topicName": "Topic 5",
  "subTopics": [
    {
      "subTopicName": "SubTopic 2"
    },
    {
      "subTopicName": "SubTopic 3"
    }
  ]
}

###

PUT http://localhost:8080/api/topics/3
Content-Type: application/json

{
  "topicName": "Topic 2",
  "subTopics": [
    {
      "subTopicName": "SubTopic 1"
    },
    {
      "subTopicName": "New SubTopic 3"
    }
  ]
}

###

DELETE http://localhost:8080/api/topics/5

###
